### PR TITLE
(FM-5236) Use double quotes so $key is interpolated

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by jpogran** [comment]
@binford2k linter is complaining about variable not being enclosed in {}

**Comment by jpogran** [comment]
@puppetlabs/windows comments? Otherwise I'm 👍

**Comment by ferventcoder** [comment]
Squash those commits and 👍

**Comment by binford2k** [comment]
mind if I squash/merge? I'm curious to see what it does.

**Pull request merged**
