### PR TITLE
(MODULES-3195) Fix WOW64 Constant Definition

### PR DESCRIPTION
**Pull request by zshahan**
REF: https://tickets.puppetlabs.com/browse/MODULES-3195

I took the third option as mentioned by Josh Cooper in the ticket.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Can you please update the commit message to say `(MODULES-3195) Fix WOW64 Constant Definition` and then update the git commit body to include more information about what you are doing and why it is pertinent (you could probably copy some of what Josh mentioned in the ticket)?

Thanks!

**Comment by david-caldwell** [comment]
Please merge this pull request

**Comment by ferventcoder** [comment]
@david-caldwell Sure :D

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/puppetlabs/puppetlabs-registry/commit/17ef3174db584846ab6b932af5e2fff5a4bb864a

**Pull request closed without merging**
